image: ubuntu:latest


stages:
  - build

services:
  - docker:dind

build:
  stage: build
  script:
    - 'apt-get update && apt-get --yes install curl'
    - ./build.sh
    - ./build/upload.sh
  only:
    - tags